var exam=[
   {
        "id":1,
        "question":"1+1=?",
        "ansItem":[
            {ans:"A",item:"4"},
            {ans:"B",item:"3"},
            {ans:"C",item:"2"},
            {ans:"D",item:"1"}
        ],
        "answer":"C"
    },
    {
        "id":2,
        "question":"1+1=?",
        "ansItem":[
            {ans:"1",item:"4"},
            {ans:"2",item:"3"},
            {ans:"3",item:"2"},
            {ans:"4",item:"1"}
        ],
        "answer":"3"
    },
    {
        "id":3,
        "question":"一加一等於多少？",
        "ansItem":[
            {ans:"A",item:"一"},
            {ans:"B",item:"二"},
            {ans:"C",item:"三"},
            {ans:"D",item:"四"}
        ],
        "answer":"C"
    },
    {
        "id":4,
        "question":"一加一等於多少？",
        "ansItem":[
            {ans:"A",item:"一"},
            {ans:"B",item:"二"},
            {ans:"C",item:"2"},
            {ans:"D",item:"Two"},
            {ans:"E",item:"0"},
            {ans:"F",item:"Zero"}
        ],
        "answer":"B,C,D"
    },
    {
        "id":5,
        "question":"一加一等於多少？",
        "ansItem":[
            {ans:"1",item:"一"},
            {ans:"2",item:"二"},
            {ans:"3",item:"2"},
            {ans:"4",item:"Two"},
            {ans:"5",item:"0"},
            {ans:"6",item:"Zero"}
        ],
        "answer":"2,3,4"
    }
]